name: CI Pipeline
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # at minute 0, every 5th hour
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Hello World!"
      - name: unit-test
        run: sleep 10
      - name: test
        run: echo "Hello World!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Hello World!"
